### PR TITLE
set default grade 'A' to all subjects

### PR DESCRIPTION
**Pull request by pansitwattana**

### CODE REVIEW

**Comment by pansitwattana** [comment]
done it. 
By the way, I found problem when a subject such as Learning Through Activities should set default grade by 'S', but now current code set to 'A'. It will make wrong expected grade

**Review by tmwatchanan — APPROVED** [review]
Okay. I see the problem. It looks like we need to find a way we can classify between a normal course (with grade A to F) and otherwise (with S and U).

**Comment by pansitwattana** [comment]
Okay, I'll open a new issue, then close this one.

**Comment by tmwatchanan** [comment]
This change makes developers need to inspect information about all courses in order to discriminate a normal course (with grade A to Z) and otherwise (with special grades, like S, U, all that jazz). So we opened the new issue #4.

**Pull request closed without merging**
